name = "hello-world-worker"
main = "index.ts"
compatibility_date = "2024-01-01"

# Account ID - replace with your Cloudflare Account ID
# account_id = "your-account-id-here"

# Workers configuration
[env.production]
name = "hello-world-worker"
workers_dev = true
