name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}
          VITE_EMPLOYEES_PASSWORD: ${{ secrets.VITE_EMPLOYEES_PASSWORD }}
          VITE_PAYROLL_PASSWORD: ${{ secrets.VITE_PAYROLL_PASSWORD }}
          VITE_MANAGE_REQUESTS_PASSWORD: ${{ secrets.VITE_MANAGE_REQUESTS_PASSWORD }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lkm-hr-system
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy summary
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🌐 Your app is live on Cloudflare Pages"
